# 🏋️ Ejercicio 2 - Práctica
**Dataset:** `../docs/product_activity.csv`

10 ejercicios cortos para practicar. ¡Vamos!

In [1]:
import pandas as pd

df = pd.read_csv('../docs/product_activity.csv')

---
## 1 - Info general
Usa `.info()` para ver un resumen del DataFrame.

In [2]:
# Tu código aqui
display(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8782 entries, 0 to 8781
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            8782 non-null   str
 1   created_at         8782 non-null   str
 2   country            8782 non-null   str
 3   plan_type          8782 non-null   str
 4   user_age           8028 non-null   float64
 5   post_id            8782 non-null   str
 6   post_category      8782 non-null   str
 7   post_created_at    8782 non-null   str
 8   votes_received     8782 non-null   int64
 9   user_total_posts   8782 non-null   int64
 10  days_since_signup  8782 non-null   int64
 11  device_type        8782 non-null   str
dtypes: float64(1), int64(3), str(8)
memory usage: 823.4 KB

None

---
## 2 - Últimas filas y muestra
Muestra las **últimas 3 filas** con `tail()` y una **muestra aleatoria de 5 filas** con `sample()`.

In [4]:
# Tu código aquí
print(f"Ultima 3 filas {df.tail(3)}")
print(f"Aleatorio {df.sample(5, random_state=42)}")

Ultima 3 filas      user_id           created_at country    plan_type  user_age   post_id  \
8779  U20008  2025-07-01T09:00:00      PE          pro      19.0  P0099008
8780  U20009  2025-08-01T10:10:10      CO  enterprise+      45.0  P0099009
8781  U20010  2025-09-01T05:05:05      ES         free       NaN  P0099010

     post_category      post_created_at  votes_received  user_total_posts  \
8779        sp0rts  2025-07-02T09:00:00               7                 6
8780     education  2025-08-03T10:10:10               0                 2
8781          tech  2025-09-02T05:05:05               9                 1

      days_since_signup device_type
8779                  1      mobile
8780                  2     desktop
8781                  1       phone
Aleatorio      user_id           created_at country plan_type  user_age   post_id  \
2697  U01585  2024-03-12T07:46:01      CL       pro      25.0  P0006791
3933  U01266  2025-03-07T06:42:41      US       pro      26.0  P0005418
7318  U01348  2024-08-19T01:43:46      BR      free      25.0  P0005761
3181  U00967  2024-01-17T02:25:23      ES      free      24.0  P0004163
7790  U00298  2025-07-09T19:54:32      PY      free      38.0  P0001315

     post_category      post_created_at  votes_received  user_total_posts  \
2697       science  2024-05-08T03:09:04              19                16
3933        gaming  2025-03-14T16:39:41               8                 5
7318       sciense  2024-09-19T20:05:35              11                 6
3181         music  2024-02-17T11:53:47               3                38
7790        sports  2025-07-11T16:33:20              12                13

      days_since_signup device_type
2697                 57         web
3933                  7      mobile
7318                 31         web
3181                 31      mobile
7790                  2         web

---
## 3 - Selección de columnas
Crea un nuevo DataFrame solo con `user_id`, `country` y `votes_received`. Muestra las primeras 5 filas.

In [5]:
# Tu código aquí
df_seleccion = df[['user_id', 'country', 'votes_received']]
df_seleccion.head()

  user_id country  votes_received
0  U01988      PY               7
1  U00236      BR               1
2  U00791      CL              11
3  U01522      US               5
4  U01092      PY               7

---
## 4 - Conteo por país
¿Cuántos registros hay por cada `country`? Ordénalos de mayor a menor.

In [6]:
# Tu código aquí
df['country'].value_counts().sort_values(ascending=False)

country
US    1928
BR    1656
AR    1199
PY     859
MX     835
CL     569
ES     568
CO     510
PE     403
UY     255
Name: count, dtype: int64

---
## 5 - Filtro con múltiples condiciones
Filtra los registros donde `country` sea `'US'` **y** `votes_received` sea mayor a 10. ¿Cuántos hay?

In [13]:
# Tu código aquí
filtro = df[(df['country'] == 'US') & (df['votes_received'] > 10)]
print(len(filtro))
filtro.head()

356

,user_id,created_at,country,plan_type,user_age,post_id,post_category,post_created_at,votes_received,user_total_posts,days_since_signup,device_type
33,U01652,2025-12-25T01:16:57,US,free,NaN,P0007121,tech,2025-12-25T09:37:31,14,2,0,mobile
51,U01900,2025-05-08T09:07:38,US,enterprise,38.0,P0008168,life,2025-05-13T20:28:35,20,7,5,web
63,U00398,2025-07-30T13:24:25,US,free,NaN,P0001719,travel,2025-09-26T14:13:32,11,12,58,mobile
70,U00936,2024-09-20T04:51:03,US,enterprise,24.0,P0004052,travel,2024-10-11T21:33:56,25,4,21,mobile
77,U01136,2024-06-10T06:22:40,US,free,16.0,P0004835,music,2024-06-13T10:01:15,19,3,3,mobile

---
## 6 - Máximo y mínimo
Encuentra el **máximo y mínimo** de `user_age`. Muestra la fila completa del usuario con más votos recibidos.

In [12]:
# Tu código aquí
print(df['user_age'].max())
print(df['user_age'].min())
print(df.loc[df['votes_received'].idxmax()])

58.0
16.0
user_id                           U01223
created_at           2024-06-10T09:14:00
country                               CO
plan_type                           free
user_age                            16.0
post_id                         P0005230
post_category                    finanse
post_created_at      2024-06-12T12:41:29
votes_received                        74
user_total_posts                      15
days_since_signup                      2
device_type                          web
Name: 4514, dtype: object

---
## 7 - Agrupar y contar
Agrupa por `post_category` y cuenta cuántos registros tiene cada una. Muestra las **5 categorías con más registros**.

In [14]:
# Tu código aquí
df.groupby('post_category').size().sort_values(ascending=False).head(5)

post_category
tech       1187
life        913
sports      899
science     753
finance     739
dtype: int64

---
## 8 - Mediana y suma
Calcula la **mediana** de `days_since_signup` y la **suma total** de `votes_received`.

In [16]:
# Tu código aquí
mediana = df['days_since_signup'].median()
suma = df['votes_received'].sum()

print(mediana)
print(suma)

17.0
60757

---
## 9 - Reemplazar nulos
Reemplaza los nulos de `user_age` con la **mediana** de esa columna. Verifica que ya no haya nulos.

In [18]:
# Tu código aquí
mediana = df['user_age'].median()
print(mediana)
df['user_age'] = df['user_age'].fillna(mediana)
print(f"no nulos despues {df['user_age'].isnull().sum()}")

28.0
no nulos despues 0

---
## 10 - Usuarios únicos
¿Cuántos `user_id` **únicos** hay? ¿Cuántos registros totales? Calcula el promedio de registros por usuario.

In [24]:
# Tu código aquí
unico = df['user_id'].nunique()
total = len(df)
promedio = total/unico

print(f'{promedio:.2f}')

4.37